# Generated by Django 5.2.17 on 2026-09-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='follow_up_completed',
            field=models.BooleanField(default=False),
        ),
    ]
