# Generated by Django 5.2.17 on 2026-09-11 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('lead', 'Potansiyel'), ('qualified', 'Nitelikli'), ('proposal', 'Teklif'), ('negotiation', 'Müzakere'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi')], default='lead', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
